name: Push image to Amazon ECR and update Amazon Lambda function image url

on:
  push:
    branches:
      - lambda/deploy

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: crawler
  LAMBDA_FUNCTION: tistory_crawler
  WORKING_DIRECTORY: ./lambda

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          echo "IMAGAE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $IMAGAE_URI --build-arg LAMBDA_ENV=prod .
          docker push $IMAGAE_URI
      - name: Update image uri of Lambda layer
        run: echo "update Lambda image uri to $IMAGAE_URI"
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION --image-uri $IMAGAE_URI
